<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-01T18:20:33 IST" name="Suite" finished-at="2023-12-01T18:20:36 IST" duration-ms="2747">
    <groups>
    </groups>
    <test started-at="2023-12-01T18:20:33 IST" name="Test" finished-at="2023-12-01T18:20:36 IST" duration-ms="2747">
      <class name="com.automation.businesscomponents.TestMe">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.automation.businesscomponents.TestMe@662706a7]" started-at="2023-12-01T18:20:31 IST" name="setUp" finished-at="2023-12-01T18:20:33 IST" duration-ms="2158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.automation.businesscomponents.TestMe@662706a7]" started-at="2023-12-01T18:20:36 IST" name="quite" finished-at="2023-12-01T18:20:36 IST" duration-ms="312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- com.automation.businesscomponents.TestMe -->
      <class name="com.automation.businesscomponents.Login">
        <test-method signature="swagLabNavigation()[pri:0, instance:com.automation.businesscomponents.Login@38875e7d]" started-at="2023-12-01T18:20:33 IST" name="swagLabNavigation" finished-at="2023-12-01T18:20:35 IST" duration-ms="1783" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- swagLabNavigation -->
        <test-method signature="login()[pri:1, instance:com.automation.businesscomponents.Login@38875e7d]" started-at="2023-12-01T18:20:35 IST" name="login" finished-at="2023-12-01T18:20:36 IST" duration-ms="938" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at org.testng.Assert.assertFalse(Assert.java:88)
at com.automation.base.LoginBase.loginSwag(LoginBase.java:31)
at com.automation.businesscomponents.Login.login(Login.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- com.automation.businesscomponents.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
